name: mage_case
version: '1.0'
config-version: 2

profile: postgres_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  mage_case:
    staging:
      +schema: staging
      +materialized: view
    data_mart:
      +schema: mart
      +materialized: table
