version: '3.9'

services:
  mageai:
    build: .
    ports:
      - "6789:6789"
    volumes:
      - ./mage_project:/home/src/mage_project
      - ./data:/home/src/data
    environment:
      - ENV=dev
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET=mage-bucket
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
